### ISSUE TITLE
Adding id attribute to top level svg

### ISSUE THREAD

**Issue by enykeev** [VictorCazanave/svg-maps#40] opened 2020-05-19 14:54 UTC
I'm wondering if you'll be willing to extend a list of svg attributes with an id. This is a requirement for svg file to be used in `<use />` and it would allow to import and style maps at large like

```
    <svg viewBox={map.viewBox} xmlns="http://www.w3.org/2000/svg" className="map">
      <use href={mapFilepath + '#world'} fill="gray" />
      {
        map.locations
          .filter(loc => targets.has(loc.id))
          .map(loc => {
            return <path key={loc.id} d={loc.path} fill="red" />
          })
      }
    </svg>
```

I'm willing to provide a PR, but I've noticed that contribution guideline specifically mentions not to do such a change.

**Comment by VictorCazanave** [comment] 2020-05-20 02:04
I'm not familiar with `<use>`, I just understand it allows to duplicate nodes from within the SVG document or from an external SVG document.
I think it's currently possible for the locations because they all have a unique id. However I don't understand why it's needed for the whole SVG document 🤔
What is the advantage of using `<use href="world.svg#world" />` instead of directly putting `<svg>...world map...</svg>`?

I'm not sure importing several maps in the same SVG document is a common use case, but if it's really useful, an id can be added to all the maps.

**Comment by enykeev** [comment] 2020-05-20 09:56
Fair enough.

Correct me if I'm wrong, but from what I understand, you can not just put an svg file into html via something like `<svg href="world.svg" />`. You can use `<img>` or `background-image`, but the svg file will be rasterized by browser ahead of time and can not be styled. You can iterate over an array the way you do in `react-svg-maps`, but it seems comparatively computationally intensive and produces a whole lot of DOM nodes.

Currently, I'm operating under an assumption that using `<use>` is more efficient than rebuilding svg object from scratch while still allowing to style the entire map. The assumption that needs to be confirmed.

Another assumption of mine is that adding an `id` attribute while may not be strictly backward compatible, by itself should not break anything unless the page already uses same `id` somewhere else. It is not unrealistic, but can be mitigated with namespacing.

I've personally already mitigated the problem for myself by just forking and republishing the package with the change for personal use, but the issue might still prove useful if someone else will be having the same problem and could potentially chip in on the discussion regarding benefits of one approach over another.

**Comment by VictorCazanave** [comment] 2020-05-23 02:25
> Correct me if I'm wrong, but from what I understand, you can not just put an svg file into html via something like `<svg href="world.svg" />`. You can use `<img>` or `background-image`, but the svg file will be rasterized by browser ahead of time and can not be styled. You can iterate over an array the way you do in react-svg-maps, but it seems comparatively computationally intensive and produces a whole lot of DOM nodes.

Yes, I think you're right. However it looks like `<use>` with an external file has [some limitations](https://css-tricks.com/svg-use-with-external-reference-take-2/#article-header-id-4) which needs to be confirmed because it's an "old" article.
If you use a module bundler (like webpack), another solution could be to add a loader (like [svg-inline-loader](https://webpack.js.org/loaders/svg-inline-loader/)) to import the SVG file in the DOM.

> Another assumption of mine is that adding an id attribute while may not be strictly backward compatible, by itself should not break anything unless the page already uses same id somewhere else. It is not unrealistic, but can be mitigated with namespacing.

I agree with you. To prevent a backward incompatibility I think the major version can be incremented (v1.x.y -> v2.0.0).

> I've personally already mitigated the problem for myself by just forking and republishing the package with the change for personal use, but the issue might still prove useful if someone else will be having the same problem and could potentially chip in on the discussion regarding benefits of one approach over another

Actually I don't mind to add an id on `<svg>`, if it can help few people (even only one). I was just curious about the use case 😄 
If you still need it, feel free to open a PR to update all the maps and the contribution guideline.

**Comment by VictorCazanave** [comment] 2020-08-15 07:31
Hi @enykeev,
Did you find a solution? I'd like to close this issue if there is nothing to do in this repository.

**Comment by enykeev** [comment] 2020-08-15 10:35
Thanks for letting me know. Go ahead and close it.

--
Кирилл Изотов

**Closed** 2020-08-15 10:37 UTC
Labels: enhancement, question
